[workspace]
name = "mitofinder_pixi"
description = "Ambiente  Pixi reproduzindo MitoFinder"
channels = ["conda-forge", "bioconda"]
authors = ["Arthur Gonçalves <arthur.tmnk@gmail.com>"]
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
#Install MitoFinder
install_mitofinder = """
git clone https://github.com/RemiAllio/MitoFinder.git ;
cd MitoFinder;
bash ./install.sh
"""

#Install Pillow (Optional if you want to generate images for annotated contigs)
install_pillow = "pip install pillow==6.2.2"

#Calling the tool
mitofinder = "/array1/arthurgdt/cleberi/mfinder/MitoFinder/mitofinder"

#Test assembly and annotation
test1 = """
cd /array1/arthurgdt/cleberi/mfinder/MitoFinder/test_case/;
../mitofinder -j Aphaenogaster_megommata_SRR1303315 -1 Aphaenogaster_megommata_SRR1303315_R1_cleaned.fastq.gz -2 Aphaenogaster_megommata_SRR1303315_R2_cleaned.fastq.gz -r reference.gb -o 5 -p 8 -m 20 --override  
"""

#Test only annotation
test2 = """
cd /array1/arthurgdt/cleberi/mfinder/MitoFinder/test_case/;
../mitofinder -j Hospitalitermes_medioflavus_NCBI -a Hospitalitermes_medioflavus_NCBI.fasta -r Hospitalitermes_medioflavus_NCBI.gb -o 5
""" 

[dependencies]
#Languages
python = "2.7.*"
perl = "*"
openjdk = "*"

#Python ecossystem
pip = ">=20.1.1,<21"

#Other dep
automake = "*"
autoconf = "*"