[workspace]
name = "bbtols_env_pixi"
channels = ["conda-forge", "bioconda"]
description = "Ambiente dos pre-requisitos para utilizar o BBtols"
authors = ["Arthur Goncalves <arthur.tmnk@gmail.com>"]
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

bbmap == "40.02"
openjdk = ">=25"
